"""PDF report generation using WeasyPrint."""
from decimal import Decimal
from io import BytesIO

from weasyprint import HTML


def _to_decimal(value: object) -> Decimal:
    if isinstance(value, Decimal):
        return value
    return Decimal(str(value))


def render_report_pdf(
    company_name: str,
    reporting_year: int,
    total_kg_co2e: Decimal,
    scope_1_kg: Decimal,
    scope_2_kg: Decimal,
    scope_3_kg: Decimal,
    scope_3_breakdown: dict[str, Decimal],
    executive_summary: str,
    methodology_notes: str,
    assumptions_limitations: str,
    emission_factor_citations: list[dict],
) -> bytes:
    """Generate PDF bytes for a carbon disclosure report."""
    total_kg_co2e = _to_decimal(total_kg_co2e)
    scope_1_kg = _to_decimal(scope_1_kg)
    scope_2_kg = _to_decimal(scope_2_kg)
    scope_3_kg = _to_decimal(scope_3_kg)
    total_tco2e = total_kg_co2e / Decimal("1000")

    scope3_rows = ""
    for cat, val in (scope_3_breakdown or {}).items():
        val_dec = _to_decimal(val)
        scope3_rows += (
            f"<tr><td>{cat}</td><td>{val_dec:.2f}</td>"
            f"<td>{(val_dec / Decimal('1000')):.2f}</td></tr>"
        )

    citations_rows = ""
    for c in emission_factor_citations or []:
        source = c.get("source", "")
        ref = c.get("url_or_ref", "")
        citations_rows += f"<tr><td>{source}</td><td>{ref}</td></tr>"

    html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Carbon Disclosure Report - {company_name}</title>
    <style>
        body {{ font-family: Georgia, serif; margin: 40px; line-height: 1.5; color: #333; }}
        h1 {{ font-size: 24px; border-bottom: 2px solid #2d5a27; padding-bottom: 8px; }}
        h2 {{ font-size: 18px; margin-top: 24px; color: #2d5a27; }}
        table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
        th, td {{ border: 1px solid #ccc; padding: 8px 12px; text-align: left; }}
        th {{ background: #f5f5f5; font-weight: 600; }}
        .summary {{ background: #f9f9f9; padding: 16px; margin: 16px 0; border-radius: 4px; }}
        .footer {{ margin-top: 40px; font-size: 12px; color: #666; }}
    </style>
</head>
<body>
    <h1>Carbon Disclosure Report</h1>
    <p><strong>{company_name}</strong> | Reporting Year: {reporting_year}</p>

    <h2>Executive Summary</h2>
    <div class="summary">{executive_summary}</div>

    <h2>Annual Emissions Total</h2>
    <table>
        <tr><th>Metric</th><th>kg CO₂e</th><th>tCO₂e</th></tr>
        <tr><td>Total</td><td>{total_kg_co2e:.2f}</td><td>{total_tco2e:.2f}</td></tr>
    </table>

    <h2>Scope Breakdown</h2>
    <table>
        <tr><th>Scope</th><th>kg CO₂e</th><th>tCO₂e</th></tr>
        <tr><td>Scope 1 (Direct)</td><td>{scope_1_kg:.2f}</td><td>{(scope_1_kg / Decimal('1000')):.2f}</td></tr>
        <tr><td>Scope 2 (Indirect - Energy)</td><td>{scope_2_kg:.2f}</td><td>{(scope_2_kg / Decimal('1000')):.2f}</td></tr>
        <tr><td>Scope 3 (Other Indirect)</td><td>{scope_3_kg:.2f}</td><td>{(scope_3_kg / Decimal('1000')):.2f}</td></tr>
    </table>
"""

    if scope3_rows:
        html_content += f"""
    <h2>Scope 3 Category Breakdown</h2>
    <table>
        <tr><th>Category</th><th>kg CO₂e</th><th>tCO₂e</th></tr>
        {scope3_rows}
    </table>
"""

    html_content += f"""
    <h2>Methodology</h2>
    <p>{methodology_notes}</p>

    <h2>Assumptions & Limitations</h2>
    <p>{assumptions_limitations}</p>

    <h2>Emission Factor Citations</h2>
    <table>
        <tr><th>Source</th><th>Reference</th></tr>
        {citations_rows if citations_rows else "<tr><td colspan='2'>EPA, DEFRA, Cloud Provider sustainability reports</td></tr>"}
    </table>

    <div class="footer">
        <p>This report was generated by Carbonly. Emissions are calculated as activity data × emission factors. 
        Each estimate tracks data quality (measured/estimated/manual), assumptions, and confidence scores for auditability.</p>
    </div>
</body>
</html>
"""

    buf = BytesIO()
    HTML(string=html_content).write_pdf(buf)
    return buf.getvalue()
